# Generated by Django 5.2.8 on 2025-12-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20251230_1908'),
    ]

    operations = [
    ]
