# Generated by Django 5.2.8 on 2026-01-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
        ('blog', '0002_create_category'),
    ]

    operations = [
    ]
