# Generated by Django 5.2.8 on 2026-01-14 14:46

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
    ("blog", "0002_alter_post_status"),
]


    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
